title: Latex Course
email: mobergmann@pm.me
description: >-
  Noch eine Website, die versucht einem einfach und schnell Latex beizubringen.
#baseurl: ""
#url: "https://mobergmann.github.io/latex-course/"
github_username: mobergmann

# Build settings
markdown: kramdown
theme: "just-the-docs"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# Theme settings
search_enabled: false
color_scheme: dark

# Exclude from processing.
exclude:
  - README.md
